export const KEY_BOTTOM_TAB_NAVIGATION = 'bottomTabNavigator'
export const SCREEN_HOME = 'homeScreen'
export const SCREEN_PROFILE = 'profile'
export const SCREEN_SEARCH = 'SeachScreen'
export const SCREEN_NOTIFICATION = 'notificartionScreen'
export const SCREEN_EDIT = 'editScreen'